### ISSUE TITLE
Title is very long

### ISSUE THREAD

**Issue by spcanelon** [LizHareDogs/iwdba2021#2]

**Comment by spcanelon** [comment]
@LizHareDogs, indeed! Haha. Right now it takes up over half of the vertical space on the slide. It also overlaps with your personal logo which is currently on the upper right corner of the slide. I'll give this some thought but I'm thinking a solution will involve reducing the heading font sizes a little and maybe the padding around the letters so that when a heading takes up more than one line (like with the title or with [slide 14](https://lizharedogs.github.io/iwdba2021/#14)) it doesn't take up quite so much space but is still clear to read.

**Comment by LizHareDogs** [comment]
The best thing would be to change the title, but I think I'm stuck with it since that's what I submitted.

It's so long that making the font smaller will probably be necessary no matter what else we do.

Maybe that first slide could just have the title and the conference name, then the next slide would have the authors?
